### ISSUE TITLE
About UNITOPATHO features

### ISSUE THREAD

**Issue by sky1652169058** [TencentAILabHealthcare/ReMix#1]
Hi Yang!
I'm very intresting about your work, i recurrented your result on Camelyon16 dataset, so i want to recurrent it on UNITOPATHO. Are you willing to share the features of UNITOPATHO you use so that i can recurrent under same conditions?
I'm looking forward to your favourable reply!

**Comment by Jiawei-Yang** [comment]
Hi there.

Sorry for the late reply. I didn't get a notification of this issue.

For UniToPatho features, you may find a copy of my features from [this link](https://drive.google.com/drive/folders/1XTx5rfXCxdQc5Gwt7xoMnt3QuId0glMV?usp=sharing).

Currently, I have left Tencent and cannot verify if these features are exactly the ones I used for the MICCAI, but I think they are the ones. Check them and notify me if there is any issue.

BTW, you can reach me via [this repo](https://github.com/Jiawei-Yang/ReMix) instead for a timely response, or directly send me an email.

**Comment by sky1652169058** [comment]
> Hi there.
> 
> Sorry for the late reply. I didn't get a notification of this issue.
> 
> For UniToPatho features, you may find a copy of my features from [this link](https://drive.google.com/drive/folders/1XTx5rfXCxdQc5Gwt7xoMnt3QuId0glMV?usp=sharing).
> 
> Currently, I have left Tencent and cannot verify if these features are exactly the ones I used for the MICCAI, but I think they are the ones. Check them and notify me if there is any issue.
> 
> BTW, you can reach me via [this repo](https://github.com/Jiawei-Yang/ReMix) instead for a timely response, or directly send me an email.

Thanks for your kind help！

Wish you a bright future and look forward to your new paper！
