### ISSUE TITLE
why the precision, recall and accuracy are calculated after binarization?

### ISSUE THREAD

**Issue by HHHedo** [TencentAILabHealthcare/ReMix#2]
Hi,
Thank you for your great work!
When I reproduce your work, I found the precision, recall and accuracy are calculated after binarization. The results are higher than the original prediction in precision and recall. Is that reasonable?
Looking forward to your help!

Best,
Tiancheng Lin

**Comment by Jiawei-Yang** [comment]
I'm going to close this issue as it has been discussed in another place ([here](https://github.com/Jiawei-Yang/ReMix/issues/2#issuecomment-1288229407)).
